// Generates lib/i18n/translations.dart from the web app's translations.ts,
// so the web (TAG) and Flutter apps share a single source of truth.
//
// Usage (from TAG_CROSSPLATFORM): node tool/gen_translations.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tsPath = resolve(root, '../TAG/src/i18n/translations.ts');
const outPath = resolve(root, 'lib/i18n/translations.dart');

const require = createRequire(resolve(root, '../TAG/package.json'));
const esbuild = require('esbuild');

const source = readFileSync(tsPath, 'utf8');

// Parse the `Translations` interface for parameter types.
const iface = source.match(/export interface Translations \{([\s\S]*?)\n\}/)[1];
const signatures = new Map();
for (const line of iface.split('\n')) {
  const m = line.match(/^\s*(\w+):\s*(.+);\s*$/);
  if (!m) continue;
  const [, key, type] = m;
  const fn = type.match(/^\((.*)\)\s*=>\s*string$/);
  if (!fn) {
    signatures.set(key, null);
    continue;
  }
  const params = fn[1]
    .split(',')
    .map((p) => p.trim())
    .filter(Boolean)
    .map((p) => p.split(':').map((s) => s.trim())[1]);
  signatures.set(key, params);
}

const dartType = (tsType) =>
  ({ string: 'String', number: 'int', boolean: 'bool' })[tsType] ?? 'Object';

// charset utf8: keep Cyrillic etc. as-is (esbuild's default rewrites it to \uXXXX escapes).
const { code } = esbuild.transformSync(source, { loader: 'ts', format: 'esm', charset: 'utf8' });
const mod = await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);

const escape = (s) =>
  s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$/g, '\\$').replace(/\n/g, '\\n');

// Convert a JS template literal *source* body into a Dart single-quoted string
// literal, keeping `${...}` interpolations (JS ternaries with double quotes are
// valid Dart). The body is still JS source, so its backslash escapes (\n, \uXXXX,
// \") are already valid Dart and pass through untouched.
function templateToDart(body) {
  let out = '';
  let i = 0;
  while (i < body.length) {
    if (body[i] === '$' && body[i + 1] === '{') {
      let depth = 1;
      let j = i + 2;
      while (depth > 0) {
        if (body[j] === '{') depth++;
        else if (body[j] === '}') depth--;
        j++;
      }
      out += '${' + body.slice(i + 2, j - 1).trim() + '}';
      i = j;
    } else if (body[i] === '\\') {
      // JS-only escapes: \` and \$ are plain characters in a Dart '...' string.
      const next = body[i + 1];
      out += next === '`' ? '`' : next === '$' ? '\\$' : body[i] + next;
      i += 2;
    } else {
      out += body[i] === "'" ? "\\'" : body[i] === '$' ? '\\$' : body[i];
      i++;
    }
  }
  return `'${out}'`;
}

function fnToDart(key, fn, paramTypes) {
  const src = fn.toString();
  const m = src.match(/^\(?([^)=]*)\)?\s*=>\s*`([\s\S]*)`$/);
  if (!m) throw new Error(`Unsupported translation function for "${key}": ${src}`);
  const names = m[1].split(',').map((s) => s.trim()).filter(Boolean);
  const params = names.map((n, idx) => `${dartType(paramTypes[idx])} ${n}`).join(', ');
  return `(${params}) => ${templateToDart(m[2])}`;
}

const keys = [...signatures.keys()];
const localeNames = Object.keys(mod.locales);

let out = `// GENERATED by tool/gen_translations.mjs from TAG/src/i18n/translations.ts.
// Do not edit by hand — edit the web translations and re-run the generator.
// ignore_for_file: non_constant_identifier_names, unnecessary_brace_in_string_interps

class Translations {
  const Translations({
${keys.map((k) => `    required this.${k},`).join('\n')}
  });

${keys
  .map((k) => {
    const params = signatures.get(k);
    const type = params ? `String Function(${params.map(dartType).join(', ')})` : 'String';
    return `  final ${type} ${k};`;
  })
  .join('\n')}
}
`;

for (const name of localeNames) {
  const locale = mod.locales[name];
  out += `\nfinal ${name} = Translations(\n`;
  for (const k of keys) {
    const value = locale[k];
    const params = signatures.get(k);
    const dart = params ? fnToDart(k, value, params) : `'${escape(value)}'`;
    out += `  ${k}: ${dart},\n`;
  }
  out += ');\n';
}

out += `\nfinal Map<String, Translations> locales = {${localeNames.map((n) => `'${n}': ${n}`).join(', ')}};\n`;

writeFileSync(outPath, out);
console.log(`Wrote ${keys.length} keys × ${localeNames.length} locales to ${outPath}`);
