// GENERATED by tool/gen_translations.mjs from TAG/src/i18n/translations.ts.
// Do not edit by hand — edit the web translations and re-run the generator.
// ignore_for_file: non_constant_identifier_names, unnecessary_brace_in_string_interps

class Translations {
  const Translations({
    required this.nav_home,
    required this.nav_history,
    required this.nav_rules,
    required this.nav_logout,
    required this.nav_toggleDark,
    required this.nav_profileAlt,
    required this.login_subtitle,
    required this.login_loading,
    required this.login_google,
    required this.ts_title,
    required this.ts_language,
    required this.ts_langEnglish,
    required this.ts_langRussian,
    required this.ts_search,
    required this.ts_searchPlaceholder,
    required this.ts_orderBy,
    required this.ts_orderByDate,
    required this.ts_orderByName,
    required this.ts_orderByLikes,
    required this.ts_orderDirection,
    required this.ts_ascending,
    required this.ts_descending,
    required this.ts_showUnverified,
    required this.ts_onlyMine,
    required this.ts_onlyFavorites,
    required this.ts_import,
    required this.ts_create,
    required this.ts_unverifiedWarning,
    required this.ts_noThemes,
    required this.ts_importTitle,
    required this.ts_importPlaceholder,
    required this.ts_public,
    required this.ts_importBtn,
    required this.ts_cancel,
    required this.td_verified,
    required this.td_unverified,
    required this.td_loading,
    required this.td_notFound,
    required this.td_back,
    required this.td_select,
    required this.td_language,
    required this.td_visibility,
    required this.td_publicLabel,
    required this.td_privateLabel,
    required this.td_createdBy,
    required this.td_teams,
    required this.td_words,
    required this.td_moreWords,
    required this.td_failedLoad,
    required this.td_failedFavorite,
    required this.td_share,
    required this.td_copied,
    required this.gs_selectTeams,
    required this.gs_selectedTeams,
    required this.gs_difficulty,
    required this.gs_difficultyHint,
    required this.gs_setDifficulty,
    required this.gs_pointsRequired,
    required this.gs_roundTimer,
    required this.gs_skipPenalty,
    required this.gs_back,
    required this.gs_startGame,
    required this.gp_round,
    required this.gp_skipped,
    required this.gp_guessed,
    required this.gp_cheatingDetected,
    required this.gp_roundPaused,
    required this.gp_skipBtn,
    required this.gp_guessedBtn,
    required this.gp_pause,
    required this.gp_paused,
    required this.gp_resume,
    required this.gp_shortcutHint,
    required this.gp_gameOver,
    required this.gp_singleWinner,
    required this.gp_multipleWinners,
    required this.gp_newGame,
    required this.gp_currentScores,
    required this.gp_score,
    required this.gp_wordsRemaining,
    required this.gp_startRound,
    required this.rr_title,
    required this.rr_hint,
    required this.rr_noWords,
    required this.rr_guessed,
    required this.rr_earned,
    required this.rr_skipped,
    required this.rr_lastWord,
    required this.rr_confirm,
    required this.gh_backToGames,
    required this.gh_gameDetails,
    required this.gh_theme,
    required this.gh_language,
    required this.gh_pointsRequired,
    required this.gh_skipPenalty,
    required this.gh_yes,
    required this.gh_no,
    required this.gh_started,
    required this.gh_ended,
    required this.gh_teams,
    required this.gh_noTeams,
    required this.gh_teamScore,
    required this.gh_gameStatus,
    required this.gh_currentRound,
    required this.gh_currentTeam,
    required this.gh_completed,
    required this.gh_inProgress,
    required this.gh_resumeGame,
    required this.gh_loading,
    required this.gh_title,
    required this.gh_back,
    required this.gh_noGames,
    required this.gh_roundTime,
    required this.ct_title,
    required this.ct_unverifiedNote,
    required this.ct_language,
    required this.ct_public,
    required this.ct_makePublic,
    required this.ct_nameLabel,
    required this.ct_namePlaceholder,
    required this.ct_nameCounter,
    required this.ct_teamsLabel,
    required this.ct_teamPlaceholder,
    required this.ct_removeTeam,
    required this.ct_addTeam,
    required this.ct_teamsCounter,
    required this.ct_teamsError,
    required this.ct_wordsLabel,
    required this.ct_importFromText,
    required this.ct_importPrompt,
    required this.ct_wordPlaceholder,
    required this.ct_difficulty,
    required this.ct_setDifficulty,
    required this.ct_addWord,
    required this.ct_wordsCounter,
    required this.ct_cancel,
    required this.ct_submit,
    required this.ct_submitting,
    required this.ct_errNameRequired,
    required this.ct_errNameTooLong,
    required this.ct_errNameTooManyWords,
    required this.ct_errTeamsCount,
    required this.ct_errTeamsDuplicate,
    required this.ct_errTeamNameTooLong,
    required this.ct_errTeamNameTooManyWords,
    required this.ct_errWordsMin,
    required this.ct_errWordsDuplicate,
    required this.ct_errWordTooLong,
    required this.ct_errWordTooManyWords,
    required this.ct_errWordDifficulty,
    required this.ct_errFailed,
    required this.et_title,
    required this.et_edit,
    required this.et_save,
    required this.et_saving,
    required this.et_nameLabel,
    required this.et_visibilityLabel,
    required this.et_addWordsLabel,
    required this.et_addWordsHint,
    required this.et_existingWords,
    required this.et_teamsLabel,
    required this.et_updatingVisibility,
    required this.et_errWordDuplicate,
    required this.et_errForbidden,
    required this.et_errFailed,
    required this.et_errVisibility,
    required this.rules_title,
    required this.rules_basicGameplay,
    required this.rules_intro,
    required this.rules_rule1,
    required this.rules_rule2,
    required this.rules_rule3,
    required this.rules_rule4,
    required this.rules_rule5,
    required this.rules_rule6,
    required this.rules_scoring,
    required this.rules_score1,
    required this.rules_score2,
    required this.rules_score3,
    required this.rules_score4,
    required this.rules_config,
    required this.rules_pointsRequired,
    required this.rules_pointsDesc,
    required this.rules_roundTimer,
    required this.rules_roundTimerDesc,
    required this.rules_skipPenalty,
    required this.rules_skipPenaltyDesc,
    required this.rules_teamsLabel,
    required this.rules_teamsDesc,
    required this.rules_themeManagement,
    required this.rules_feat1,
    required this.rules_feat2,
    required this.rules_feat3,
    required this.rules_feat4,
    required this.rules_feat5,
    required this.rules_gameFeatures,
    required this.rules_gameHistory,
    required this.rules_gameHistoryDesc,
    required this.rules_gameResumption,
    required this.rules_gameResumptionDesc,
    required this.rules_cheatingDetection,
    required this.rules_cheatingDetectionDesc,
    required this.rules_resultConfirmation,
    required this.rules_resultConfirmationDesc,
    required this.rules_howToPlay,
    required this.rules_step1,
    required this.rules_step2,
    required this.rules_step3,
    required this.rules_step4,
    required this.rules_step5,
    required this.rules_step6,
    required this.rules_difficultyLevels,
    required this.rules_veryEasy,
    required this.rules_easy,
    required this.rules_medium,
    required this.rules_hard,
    required this.rules_veryHard,
    required this.cs_cheatingTitle,
    required this.cs_cheatingDesc,
    required this.cs_pausedTitle,
    required this.cs_pausedDesc,
  });

  final String nav_home;
  final String nav_history;
  final String nav_rules;
  final String nav_logout;
  final String nav_toggleDark;
  final String nav_profileAlt;
  final String login_subtitle;
  final String login_loading;
  final String login_google;
  final String ts_title;
  final String ts_language;
  final String ts_langEnglish;
  final String ts_langRussian;
  final String ts_search;
  final String ts_searchPlaceholder;
  final String ts_orderBy;
  final String ts_orderByDate;
  final String ts_orderByName;
  final String ts_orderByLikes;
  final String ts_orderDirection;
  final String ts_ascending;
  final String ts_descending;
  final String ts_showUnverified;
  final String ts_onlyMine;
  final String ts_onlyFavorites;
  final String ts_import;
  final String ts_create;
  final String ts_unverifiedWarning;
  final String ts_noThemes;
  final String ts_importTitle;
  final String ts_importPlaceholder;
  final String ts_public;
  final String ts_importBtn;
  final String ts_cancel;
  final String td_verified;
  final String td_unverified;
  final String td_loading;
  final String td_notFound;
  final String td_back;
  final String td_select;
  final String Function(String) td_language;
  final String Function(bool) td_visibility;
  final String td_publicLabel;
  final String td_privateLabel;
  final String Function(String) td_createdBy;
  final String Function(int) td_teams;
  final String Function(int) td_words;
  final String Function(int) td_moreWords;
  final String td_failedLoad;
  final String td_failedFavorite;
  final String td_share;
  final String td_copied;
  final String gs_selectTeams;
  final String Function(int, int) gs_selectedTeams;
  final String gs_difficulty;
  final String Function(int) gs_difficultyHint;
  final String Function(int) gs_setDifficulty;
  final String Function(int) gs_pointsRequired;
  final String Function(int) gs_roundTimer;
  final String gs_skipPenalty;
  final String gs_back;
  final String gs_startGame;
  final String Function(int) gp_round;
  final String gp_skipped;
  final String gp_guessed;
  final String gp_cheatingDetected;
  final String gp_roundPaused;
  final String gp_skipBtn;
  final String gp_guessedBtn;
  final String gp_pause;
  final String gp_paused;
  final String gp_resume;
  final String gp_shortcutHint;
  final String gp_gameOver;
  final String Function(String) gp_singleWinner;
  final String Function(String) gp_multipleWinners;
  final String gp_newGame;
  final String gp_currentScores;
  final String Function(int, int) gp_score;
  final String Function(int) gp_wordsRemaining;
  final String gp_startRound;
  final String rr_title;
  final String rr_hint;
  final String rr_noWords;
  final String rr_guessed;
  final String rr_earned;
  final String rr_skipped;
  final String rr_lastWord;
  final String rr_confirm;
  final String gh_backToGames;
  final String gh_gameDetails;
  final String Function(String) gh_theme;
  final String Function(String) gh_language;
  final String Function(int) gh_pointsRequired;
  final String Function(bool) gh_skipPenalty;
  final String gh_yes;
  final String gh_no;
  final String Function(String) gh_started;
  final String Function(String) gh_ended;
  final String gh_teams;
  final String gh_noTeams;
  final String Function(String, int) gh_teamScore;
  final String gh_gameStatus;
  final String Function(int) gh_currentRound;
  final String Function(String) gh_currentTeam;
  final String gh_completed;
  final String gh_inProgress;
  final String gh_resumeGame;
  final String gh_loading;
  final String gh_title;
  final String gh_back;
  final String gh_noGames;
  final String Function(int) gh_roundTime;
  final String ct_title;
  final String ct_unverifiedNote;
  final String ct_language;
  final String ct_public;
  final String ct_makePublic;
  final String ct_nameLabel;
  final String ct_namePlaceholder;
  final String Function(int, int) ct_nameCounter;
  final String ct_teamsLabel;
  final String Function(int) ct_teamPlaceholder;
  final String ct_removeTeam;
  final String ct_addTeam;
  final String Function(int, int) ct_teamsCounter;
  final String ct_teamsError;
  final String ct_wordsLabel;
  final String ct_importFromText;
  final String ct_importPrompt;
  final String Function(int) ct_wordPlaceholder;
  final String ct_difficulty;
  final String Function(int) ct_setDifficulty;
  final String ct_addWord;
  final String Function(int) ct_wordsCounter;
  final String ct_cancel;
  final String ct_submit;
  final String ct_submitting;
  final String ct_errNameRequired;
  final String ct_errNameTooLong;
  final String ct_errNameTooManyWords;
  final String ct_errTeamsCount;
  final String Function(String) ct_errTeamsDuplicate;
  final String Function(String) ct_errTeamNameTooLong;
  final String Function(String) ct_errTeamNameTooManyWords;
  final String ct_errWordsMin;
  final String Function(String) ct_errWordsDuplicate;
  final String Function(String) ct_errWordTooLong;
  final String Function(String) ct_errWordTooManyWords;
  final String Function(String) ct_errWordDifficulty;
  final String ct_errFailed;
  final String et_title;
  final String et_edit;
  final String et_save;
  final String et_saving;
  final String et_nameLabel;
  final String et_visibilityLabel;
  final String et_addWordsLabel;
  final String et_addWordsHint;
  final String Function(int) et_existingWords;
  final String et_teamsLabel;
  final String et_updatingVisibility;
  final String Function(String) et_errWordDuplicate;
  final String et_errForbidden;
  final String et_errFailed;
  final String et_errVisibility;
  final String rules_title;
  final String rules_basicGameplay;
  final String rules_intro;
  final String rules_rule1;
  final String rules_rule2;
  final String rules_rule3;
  final String rules_rule4;
  final String rules_rule5;
  final String rules_rule6;
  final String rules_scoring;
  final String rules_score1;
  final String rules_score2;
  final String rules_score3;
  final String rules_score4;
  final String rules_config;
  final String rules_pointsRequired;
  final String rules_pointsDesc;
  final String rules_roundTimer;
  final String rules_roundTimerDesc;
  final String rules_skipPenalty;
  final String rules_skipPenaltyDesc;
  final String rules_teamsLabel;
  final String rules_teamsDesc;
  final String rules_themeManagement;
  final String rules_feat1;
  final String rules_feat2;
  final String rules_feat3;
  final String rules_feat4;
  final String rules_feat5;
  final String rules_gameFeatures;
  final String rules_gameHistory;
  final String rules_gameHistoryDesc;
  final String rules_gameResumption;
  final String rules_gameResumptionDesc;
  final String rules_cheatingDetection;
  final String rules_cheatingDetectionDesc;
  final String rules_resultConfirmation;
  final String rules_resultConfirmationDesc;
  final String rules_howToPlay;
  final String rules_step1;
  final String rules_step2;
  final String rules_step3;
  final String rules_step4;
  final String rules_step5;
  final String rules_step6;
  final String rules_difficultyLevels;
  final String rules_veryEasy;
  final String rules_easy;
  final String rules_medium;
  final String rules_hard;
  final String rules_veryHard;
  final String cs_cheatingTitle;
  final String cs_cheatingDesc;
  final String cs_pausedTitle;
  final String cs_pausedDesc;
}

final en = Translations(
  nav_home: 'Home',
  nav_history: 'History',
  nav_rules: 'Rules',
  nav_logout: 'Logout',
  nav_toggleDark: 'Toggle dark mode',
  nav_profileAlt: 'Profile',
  login_subtitle: 'Themed Alias Game',
  login_loading: 'Loading...',
  login_google: 'Continue with Google',
  ts_title: 'Select Theme',
  ts_language: 'Language',
  ts_langEnglish: 'English',
  ts_langRussian: 'Russian',
  ts_search: 'Search',
  ts_searchPlaceholder: 'Search themes...',
  ts_orderBy: 'Order By',
  ts_orderByDate: 'Creation Date',
  ts_orderByName: 'Name',
  ts_orderByLikes: 'Likes',
  ts_orderDirection: 'Order Direction',
  ts_ascending: 'Ascending',
  ts_descending: 'Descending',
  ts_showUnverified: 'Show unverified themes',
  ts_onlyMine: 'Only my themes',
  ts_onlyFavorites: 'Only favorites',
  ts_import: 'Import Theme',
  ts_create: 'Create Theme',
  ts_unverifiedWarning: 'Unverified themes may contain inappropriate content',
  ts_noThemes: 'No themes available. Import or Create a theme to get started.',
  ts_importTitle: 'Import Theme',
  ts_importPlaceholder: 'Paste theme JSON here...\n\nExample format:\n{\n  "name": "My Theme",\n  "language": "en",\n  "description": {\n    "teams": ["Team 1", ...],\n    "words": { "word": { "difficulty": 1 }, ... }\n  }\n}',
  ts_public: 'Public',
  ts_importBtn: 'Import',
  ts_cancel: 'Cancel',
  td_verified: '✅ Verified',
  td_unverified: '❌ Unverified',
  td_loading: 'Loading theme details...',
  td_notFound: 'Theme not found',
  td_back: '← Back',
  td_select: 'Select Theme',
  td_language: (String lang) => 'Language: ${lang}',
  td_visibility: (bool isPublic) => 'Visibility: ${isPublic ? "Public" : "Private"}',
  td_publicLabel: 'Public',
  td_privateLabel: 'Private',
  td_createdBy: (String email) => 'Created by: ${email}',
  td_teams: (int count) => 'Teams (${count})',
  td_words: (int count) => 'Words (${count})',
  td_moreWords: (int count) => '... and ${count} more words',
  td_failedLoad: 'Failed to load theme details',
  td_failedFavorite: 'Failed to update favorite status',
  td_share: 'Share',
  td_copied: 'Copied!',
  gs_selectTeams: 'Select Teams',
  gs_selectedTeams: (int s, int t) => 'Selected: ${s} / ${t}',
  gs_difficulty: 'Difficulty',
  gs_difficultyHint: (int level) => 'Show words with difficulty ${level} or lower',
  gs_setDifficulty: (int level) => 'Set difficulty to ${level}',
  gs_pointsRequired: (int points) => 'Points Required: ${points}',
  gs_roundTimer: (int seconds) => 'Round Timer: ${seconds}s',
  gs_skipPenalty: 'Skip Penalty',
  gs_back: 'Back',
  gs_startGame: 'Start Game',
  gp_round: (int round) => 'Round ${round}',
  gp_skipped: 'Skipped',
  gp_guessed: 'Guessed',
  gp_cheatingDetected: 'Cheating detected — wait for round to end',
  gp_roundPaused: 'Round paused — finish the round so data can be saved',
  gp_skipBtn: 'Skip ❌',
  gp_guessedBtn: 'Guessed ✅',
  gp_pause: 'Pause',
  gp_paused: 'Paused',
  gp_resume: '▶️ Resume',
  gp_shortcutHint: 'Desktop shortcut: ← Skip, → Guessed',
  gp_gameOver: 'Game Over!',
  gp_singleWinner: (String name) => '${name} Wins!',
  gp_multipleWinners: (String names) => '${names} Win!',
  gp_newGame: 'New Game',
  gp_currentScores: 'Current Scores',
  gp_score: (int score, int required) => '${score} / ${required}',
  gp_wordsRemaining: (int count) => '${count} words remaining',
  gp_startRound: 'Start Round',
  rr_title: 'Round Results',
  rr_hint: 'Tap words to toggle between ✅ and ❌',
  rr_noWords: 'No words were processed in this round.',
  rr_guessed: 'Guessed',
  rr_earned: 'Earned',
  rr_skipped: 'Skipped',
  rr_lastWord: 'Last word',
  rr_confirm: 'Confirm',
  gh_backToGames: '← Back to Games',
  gh_gameDetails: 'Game Details',
  gh_theme: (String name) => 'Theme: ${name}',
  gh_language: (String lang) => 'Language: ${lang}',
  gh_pointsRequired: (int points) => 'Points Required: ${points}',
  gh_skipPenalty: (bool enabled) => 'Skip Penalty: ${enabled ? "Yes" : "No"}',
  gh_yes: 'Yes',
  gh_no: 'No',
  gh_started: (String date) => 'Started: ${date}',
  gh_ended: (String date) => 'Ended: ${date}',
  gh_teams: 'Teams',
  gh_noTeams: 'No teams data available',
  gh_teamScore: (String name, int score) => '${name}: ${score} points',
  gh_gameStatus: 'Game Status',
  gh_currentRound: (int round) => 'Current Round: ${round}',
  gh_currentTeam: (String name) => 'Current Team: ${name}',
  gh_completed: 'Completed',
  gh_inProgress: 'In Progress',
  gh_resumeGame: 'Resume Game',
  gh_loading: 'Loading game history...',
  gh_title: 'Game History',
  gh_back: '← Back',
  gh_noGames: 'No games found. Start playing to see your game history!',
  gh_roundTime: (int seconds) => 'Round Time: ${seconds}',
  ct_title: 'Create Theme',
  ct_unverifiedNote: 'New themes will be marked as unverified until admin review',
  ct_language: 'Language *',
  ct_public: 'Public',
  ct_makePublic: 'Make this theme public',
  ct_nameLabel: 'Theme Name * (max 64 chars, max 10 words)',
  ct_namePlaceholder: 'e.g., Harry Potter',
  ct_nameCounter: (int chars, int words) => '${chars}/64 characters \\u2022 ${words}/10 words',
  ct_teamsLabel: 'Teams * (exactly 10 teams, each max 64 chars, max 10 words)',
  ct_teamPlaceholder: (int i) => 'Team ${i}',
  ct_removeTeam: 'Remove',
  ct_addTeam: '+ Add Team',
  ct_teamsCounter: (int filled, int total) => '${filled} filled \\u2022 ${total} entries \\u2022 10 required',
  ct_teamsError: 'You must provide exactly 10 filled team names to create a theme.',
  ct_wordsLabel: 'Words * (at least 30 difficulty 1 words, each max 64 chars, max 10 words)',
  ct_importFromText: 'Import from Text (one per line)',
  ct_importPrompt: 'Paste one word per line, or JSON like {"hello": {"difficulty": 1}, "world": {"difficulty": 3}}:',
  ct_wordPlaceholder: (int i) => 'Word ${i}',
  ct_difficulty: 'Difficulty',
  ct_setDifficulty: (int level) => 'Set difficulty to ${level}',
  ct_addWord: '+ Add Word',
  ct_wordsCounter: (int count) => '${count} / 30 difficulty 1 words (minimum)',
  ct_cancel: 'Cancel',
  ct_submit: 'Create Theme',
  ct_submitting: 'Submitting...',
  ct_errNameRequired: 'Theme name is required',
  ct_errNameTooLong: 'Theme name must be 64 characters or less',
  ct_errNameTooManyWords: 'Theme name must be 10 words or less',
  ct_errTeamsCount: 'Theme must contain exactly 10 teams',
  ct_errTeamsDuplicate: (String d) => 'Team names must be unique. Duplicates found: ${d}',
  ct_errTeamNameTooLong: (String name) => 'Team name "${name}" must be 64 characters or less',
  ct_errTeamNameTooManyWords: (String name) => 'Team name "${name}" must be 10 words or less',
  ct_errWordsMin: 'Theme must have at least 30 difficulty 1 words',
  ct_errWordsDuplicate: (String d) => 'Words must be unique within a theme. Duplicates found: ${d}',
  ct_errWordTooLong: (String word) => 'Word "${word}" must be 64 characters or less',
  ct_errWordTooManyWords: (String word) => 'Word "${word}" must be 10 words or less',
  ct_errWordDifficulty: (String word) => 'Word "${word}" must have a difficulty between 1 and 5',
  ct_errFailed: 'Failed to create theme',
  et_title: 'Edit Theme',
  et_edit: 'Edit',
  et_save: 'Save Changes',
  et_saving: 'Saving...',
  et_nameLabel: 'Theme Name',
  et_visibilityLabel: 'Visibility',
  et_addWordsLabel: 'Add New Words',
  et_addWordsHint: 'Existing words cannot be edited or removed',
  et_existingWords: (int count) => 'Existing Words (${count})',
  et_teamsLabel: 'Teams (read-only)',
  et_updatingVisibility: 'Updating...',
  et_errWordDuplicate: (String words) => 'Words already exist in this theme: ${words}',
  et_errForbidden: 'You don\'t have permission to edit this theme',
  et_errFailed: 'Failed to save changes',
  et_errVisibility: 'Failed to update visibility',
  rules_title: 'Alias Game Rules',
  rules_basicGameplay: 'Basic Gameplay',
  rules_intro: 'Alias is a fun word-guessing game where teams compete to guess as many words as possible within a time limit.',
  rules_rule1: 'Players are divided into teams',
  rules_rule2: 'One team player plays at a time while others guess',
  rules_rule3: 'The playing team gets a word and must describe it without saying the word itself',
  rules_rule4: 'Teammates try to guess the word',
  rules_rule5: 'Points are awarded for correct guesses',
  rules_rule6: 'The round ends when time runs out or all words are used',
  rules_scoring: 'Scoring',
  rules_score1: 'Correct guess: +1 point',
  rules_score2: 'Skip penalty: -1 point (if enabled)',
  rules_score3: 'Win condition: First team to reach the target score wins',
  rules_score4: 'Tiebreaker: If no team reaches the target when words run out, the team with highest score wins',
  rules_config: 'Game Configuration',
  rules_pointsRequired: 'Points Required',
  rules_pointsDesc: 'Set the target score to win the game (default: 50 points)',
  rules_roundTimer: 'Round Timer',
  rules_roundTimerDesc: 'Time limit for each round (15-300 seconds, default: 60)',
  rules_skipPenalty: 'Skip Penalty',
  rules_skipPenaltyDesc: 'Enable/disable point deduction for skipped words',
  rules_teamsLabel: 'Teams',
  rules_teamsDesc: '2-10 teams can play simultaneously',
  rules_themeManagement: 'Theme Management',
  rules_feat1: 'Theme Creation: Create custom word themes with your own word lists',
  rules_feat2: 'Theme Import: Import themes from external sources in JSON format',
  rules_feat3: 'Filtering: Filter by difficulty, language, your themes, favorites, verified status',
  rules_feat4: 'Search: Find themes by name or description',
  rules_feat5: 'Minimum words: Each theme must have at least 30 words',
  rules_gameFeatures: 'Game Features',
  rules_gameHistory: 'Game History',
  rules_gameHistoryDesc: 'View all completed games and track statistics',
  rules_gameResumption: 'Game Resumption',
  rules_gameResumptionDesc: 'Resume unfinished games from where you left off',
  rules_cheatingDetection: 'Cheating Detection',
  rules_cheatingDetectionDesc: 'Monitors round start times to prevent unfair play',
  rules_resultConfirmation: 'Result Confirmation',
  rules_resultConfirmationDesc: 'Review and confirm round results before scoring',
  rules_howToPlay: 'How to Play',
  rules_step1: 'Choose a theme with words to guess',
  rules_step2: 'Configure game settings (points, timer, teams)',
  rules_step3: 'Take turns describing words to your team',
  rules_step4: 'Click "Guessed" for correct answers, "Skip" for difficult words',
  rules_step5: 'Review and confirm results after each round',
  rules_step6: 'Continue until a team reaches the target score',
  rules_difficultyLevels: 'Difficulty Levels',
  rules_veryEasy: 'Very Easy',
  rules_easy: 'Easy',
  rules_medium: 'Medium',
  rules_hard: 'Hard',
  rules_veryHard: 'Very Hard',
  cs_cheatingTitle: 'Cheating Detected',
  cs_cheatingDesc: 'Too many words guessed too quickly',
  cs_pausedTitle: 'Round Paused',
  cs_pausedDesc: 'Word is hidden until resumed',
);

final ru = Translations(
  nav_home: 'Главная',
  nav_history: 'История',
  nav_rules: 'Правила',
  nav_logout: 'Выйти',
  nav_toggleDark: 'Сменить тему',
  nav_profileAlt: 'Профиль',
  login_subtitle: 'Тематическая игра Alias',
  login_loading: 'Загрузка...',
  login_google: 'Войти через Google',
  ts_title: 'Выбор темы',
  ts_language: 'Язык',
  ts_langEnglish: 'Английский',
  ts_langRussian: 'Русский',
  ts_search: 'Поиск',
  ts_searchPlaceholder: 'Поиск тем...',
  ts_orderBy: 'Сортировать по',
  ts_orderByDate: 'Дате создания',
  ts_orderByName: 'Названию',
  ts_orderByLikes: 'Лайкам',
  ts_orderDirection: 'Порядок',
  ts_ascending: 'По возрастанию',
  ts_descending: 'По убыванию',
  ts_showUnverified: 'Показать непроверенные темы',
  ts_onlyMine: 'Только мои темы',
  ts_onlyFavorites: 'Только избранные',
  ts_import: 'Импорт темы',
  ts_create: 'Создать тему',
  ts_unverifiedWarning: 'Непроверенные темы могут содержать неподходящий контент',
  ts_noThemes: 'Темы не найдены. Импортируйте или создайте тему.',
  ts_importTitle: 'Импорт темы',
  ts_importPlaceholder: 'Вставьте JSON темы сюда...\n\nПример формата:\n{\n  "name": "Моя тема",\n  "language": "ru",\n  "description": {\n    "teams": ["Команда 1", ...],\n    "words": { "слово": { "difficulty": 1 }, ... }\n  }\n}',
  ts_public: 'Публичная',
  ts_importBtn: 'Импортировать',
  ts_cancel: 'Отмена',
  td_verified: '✅ Проверена',
  td_unverified: '❌ Не проверена',
  td_loading: 'Загрузка темы...',
  td_notFound: 'Тема не найдена',
  td_back: '← Назад',
  td_select: 'Выбрать тему',
  td_language: (String lang) => '\\u042F\\u0437\\u044B\\u043A: ${lang}',
  td_visibility: (bool isPublic) => '\\u0412\\u0438\\u0434\\u0438\\u043C\\u043E\\u0441\\u0442\\u044C: ${isPublic ? "\u041F\u0443\u0431\u043B\u0438\u0447\u043D\u0430\u044F" : "\u041F\u0440\u0438\u0432\u0430\u0442\u043D\u0430\u044F"}',
  td_publicLabel: 'Публичная',
  td_privateLabel: 'Приватная',
  td_createdBy: (String email) => '\\u0421\\u043E\\u0437\\u0434\\u0430\\u043D\\u043E: ${email}',
  td_teams: (int count) => '\\u041A\\u043E\\u043C\\u0430\\u043D\\u0434\\u044B (${count})',
  td_words: (int count) => '\\u0421\\u043B\\u043E\\u0432\\u0430 (${count})',
  td_moreWords: (int count) => '... \\u0438 \\u0435\\u0449\\u0451 ${count} \\u0441\\u043B\\u043E\\u0432',
  td_failedLoad: 'Не удалось загрузить тему',
  td_failedFavorite: 'Не удалось обновить статус',
  td_share: 'Поделиться',
  td_copied: 'Скопировано!',
  gs_selectTeams: 'Выбор команд',
  gs_selectedTeams: (int s, int total) => '\\u0412\\u044B\\u0431\\u0440\\u0430\\u043D\\u043E: ${s} / ${total}',
  gs_difficulty: 'Сложность',
  gs_difficultyHint: (int level) => '\\u0421\\u043B\\u043E\\u0432\\u0430 \\u0441\\u043E \\u0441\\u043B\\u043E\\u0436\\u043D\\u043E\\u0441\\u0442\\u044C\\u044E ${level} \\u0438 \\u043D\\u0438\\u0436\\u0435',
  gs_setDifficulty: (int level) => '\\u0423\\u0441\\u0442\\u0430\\u043D\\u043E\\u0432\\u0438\\u0442\\u044C \\u0441\\u043B\\u043E\\u0436\\u043D\\u043E\\u0441\\u0442\\u044C ${level}',
  gs_pointsRequired: (int points) => '\\u041E\\u0447\\u043A\\u043E\\u0432 \\u0434\\u043B\\u044F \\u043F\\u043E\\u0431\\u0435\\u0434\\u044B: ${points}',
  gs_roundTimer: (int seconds) => '\\u0422\\u0430\\u0439\\u043C\\u0435\\u0440: ${seconds}\\u0441',
  gs_skipPenalty: 'Штраф за пропуск',
  gs_back: 'Назад',
  gs_startGame: 'Начать игру',
  gp_round: (int round) => '\\u0420\\u0430\\u0443\\u043D\\u0434 ${round}',
  gp_skipped: 'Пропущено',
  gp_guessed: 'Угадано',
  gp_cheatingDetected: 'Читерство обнаружено — ждите конца раунда',
  gp_roundPaused: 'Раунд на паузе — завершите раунд для сохранения',
  gp_skipBtn: 'Пропуск ❌',
  gp_guessedBtn: 'Угадано ✅',
  gp_pause: 'Пауза',
  gp_paused: 'Пауза',
  gp_resume: '▶️ Продолжить',
  gp_shortcutHint: 'Горячие клавиши: ← Пропустить, → Угадано',
  gp_gameOver: 'Игра окончена!',
  gp_singleWinner: (String name) => '\\u041F\\u043E\\u0431\\u0435\\u0434\\u0438\\u0442\\u0435\\u043B\\u044C: ${name}',
  gp_multipleWinners: (String names) => '\\u041F\\u043E\\u0431\\u0435\\u0434\\u0438\\u0442\\u0435\\u043B\\u0438: ${names}',
  gp_newGame: 'Новая игра',
  gp_currentScores: 'Текущий счёт',
  gp_score: (int score, int required) => '${score} / ${required}',
  gp_wordsRemaining: (int count) => '\\u041E\\u0441\\u0442\\u0430\\u043B\\u043E\\u0441\\u044C \\u0441\\u043B\\u043E\\u0432: ${count}',
  gp_startRound: 'Начать раунд',
  rr_title: 'Результаты раунда',
  rr_hint: 'Нажмите на слово, чтобы изменить результат',
  rr_noWords: 'В этом раунде слова не обрабатывались.',
  rr_guessed: 'Угадано',
  rr_earned: 'Заработано',
  rr_skipped: 'Пропущено',
  rr_lastWord: 'Последнее слово',
  rr_confirm: 'Подтвердить',
  gh_backToGames: '← К играм',
  gh_gameDetails: 'Детали игры',
  gh_theme: (String name) => '\\u0422\\u0435\\u043C\\u0430: ${name}',
  gh_language: (String lang) => '\\u042F\\u0437\\u044B\\u043A: ${lang}',
  gh_pointsRequired: (int points) => '\\u041E\\u0447\\u043A\\u043E\\u0432 \\u0434\\u043B\\u044F \\u043F\\u043E\\u0431\\u0435\\u0434\\u044B: ${points}',
  gh_skipPenalty: (bool enabled) => '\\u0428\\u0442\\u0440\\u0430\\u0444 \\u0437\\u0430 \\u043F\\u0440\\u043E\\u043F\\u0443\\u0441\\u043A: ${enabled ? "\u0414\u0430" : "\u041D\u0435\u0442"}',
  gh_yes: 'Да',
  gh_no: 'Нет',
  gh_started: (String date) => '\\u041D\\u0430\\u0447\\u0430\\u0442\\u043E: ${date}',
  gh_ended: (String date) => '\\u0417\\u0430\\u0432\\u0435\\u0440\\u0448\\u0435\\u043D\\u043E: ${date}',
  gh_teams: 'Команды',
  gh_noTeams: 'Нет данных о командах',
  gh_teamScore: (String name, int score) => '${name}: ${score} \\u043E\\u0447\\u043A\\u043E\\u0432',
  gh_gameStatus: 'Статус игры',
  gh_currentRound: (int round) => '\\u0422\\u0435\\u043A\\u0443\\u0449\\u0438\\u0439 \\u0440\\u0430\\u0443\\u043D\\u0434: ${round}',
  gh_currentTeam: (String name) => '\\u0422\\u0435\\u043A\\u0443\\u0449\\u0430\\u044F \\u043A\\u043E\\u043C\\u0430\\u043D\\u0434\\u0430: ${name}',
  gh_completed: 'Завершена',
  gh_inProgress: 'В процессе',
  gh_resumeGame: 'Продолжить игру',
  gh_loading: 'Загрузка истории...',
  gh_title: 'История игр',
  gh_back: '← Назад',
  gh_noGames: 'Игры не найдены. Начните игру!',
  gh_roundTime: (int seconds) => '\\u0412\\u0440\\u0435\\u043C\\u044F \\u0440\\u0430\\u0443\\u043D\\u0434\\u0430: ${seconds}',
  ct_title: 'Создать тему',
  ct_unverifiedNote: 'Новые темы будут помечены как непроверенные до проверки администратором',
  ct_language: 'Язык *',
  ct_public: 'Публичная',
  ct_makePublic: 'Сделать тему публичной',
  ct_nameLabel: 'Название темы * (макс. 64 символа, макс. 10 слов)',
  ct_namePlaceholder: 'Например: Гарри Поттер',
  ct_nameCounter: (int chars, int words) => '${chars}/64 \\u0441\\u0438\\u043C\\u0432\\u043E\\u043B\\u043E\\u0432 \\u2022 ${words}/10 \\u0441\\u043B\\u043E\\u0432',
  ct_teamsLabel: 'Команды * (ровно 10, макс. 64 символа, макс. 10 слов)',
  ct_teamPlaceholder: (int i) => '\\u041A\\u043E\\u043C\\u0430\\u043D\\u0434\\u0430 ${i}',
  ct_removeTeam: 'Удалить',
  ct_addTeam: '+ Добавить команду',
  ct_teamsCounter: (int filled, int total) => '${filled} \\u0437\\u0430\\u043F\\u043E\\u043B\\u043D\\u0435\\u043D\\u043E \\u2022 ${total} \\u0437\\u0430\\u043F\\u0438\\u0441\\u0435\\u0439 \\u2022 \\u043D\\u0443\\u0436\\u043D\\u043E 10',
  ct_teamsError: 'Необходимо указать ровно 10 названий команд.',
  ct_wordsLabel: 'Слова * (минимум 30 слов сложности 1, макс. 64 символа, макс. 10 слов)',
  ct_importFromText: 'Импорт из текста (одно слово в строке)',
  ct_importPrompt: 'Вставьте одно слово в строке или JSON вида {"hello": {"difficulty": 1}, "world": {"difficulty": 3}}:',
  ct_wordPlaceholder: (int i) => '\\u0421\\u043B\\u043E\\u0432\\u043E ${i}',
  ct_difficulty: 'Сложность',
  ct_setDifficulty: (int level) => '\\u0423\\u0441\\u0442\\u0430\\u043D\\u043E\\u0432\\u0438\\u0442\\u044C \\u0441\\u043B\\u043E\\u0436\\u043D\\u043E\\u0441\\u0442\\u044C ${level}',
  ct_addWord: '+ Добавить слово',
  ct_wordsCounter: (int count) => '${count} / 30 \\u0441\\u043B\\u043E\\u0432 \\u0441\\u043B\\u043E\\u0436\\u043D\\u043E\\u0441\\u0442\\u0438 1 (\\u043C\\u0438\\u043D\\u0438\\u043C\\u0443\\u043C)',
  ct_cancel: 'Отмена',
  ct_submit: 'Создать тему',
  ct_submitting: 'Отправка...',
  ct_errNameRequired: 'Название темы обязательно',
  ct_errNameTooLong: 'Название темы не более 64 символов',
  ct_errNameTooManyWords: 'Название темы не более 10 слов',
  ct_errTeamsCount: 'Тема должна содержать ровно 10 команд',
  ct_errTeamsDuplicate: (String d) => '\\u041D\\u0430\\u0437\\u0432\\u0430\\u043D\\u0438\\u044F \\u043A\\u043E\\u043C\\u0430\\u043D\\u0434 \\u0434\\u043E\\u043B\\u0436\\u043D\\u044B \\u0431\\u044B\\u0442\\u044C \\u0443\\u043D\\u0438\\u043A\\u0430\\u043B\\u044C\\u043D\\u044B\\u043C\\u0438. \\u0414\\u0443\\u0431\\u043B\\u0438\\u043A\\u0430\\u0442\\u044B: ${d}',
  ct_errTeamNameTooLong: (String name) => '\\u041D\\u0430\\u0437\\u0432\\u0430\\u043D\\u0438\\u0435 \\u043A\\u043E\\u043C\\u0430\\u043D\\u0434\\u044B "${name}" \\u043D\\u0435 \\u0431\\u043E\\u043B\\u0435\\u0435 64 \\u0441\\u0438\\u043C\\u0432\\u043E\\u043B\\u043E\\u0432',
  ct_errTeamNameTooManyWords: (String name) => '\\u041D\\u0430\\u0437\\u0432\\u0430\\u043D\\u0438\\u0435 \\u043A\\u043E\\u043C\\u0430\\u043D\\u0434\\u044B "${name}" \\u043D\\u0435 \\u0431\\u043E\\u043B\\u0435\\u0435 10 \\u0441\\u043B\\u043E\\u0432',
  ct_errWordsMin: 'Тема должна содержать минимум 30 слов сложности 1',
  ct_errWordsDuplicate: (String d) => '\\u0421\\u043B\\u043E\\u0432\\u0430 \\u0434\\u043E\\u043B\\u0436\\u043D\\u044B \\u0431\\u044B\\u0442\\u044C \\u0443\\u043D\\u0438\\u043A\\u0430\\u043B\\u044C\\u043D\\u044B\\u043C\\u0438. \\u0414\\u0443\\u0431\\u043B\\u0438\\u043A\\u0430\\u0442\\u044B: ${d}',
  ct_errWordTooLong: (String word) => '\\u0421\\u043B\\u043E\\u0432\\u043E "${word}" \\u043D\\u0435 \\u0431\\u043E\\u043B\\u0435\\u0435 64 \\u0441\\u0438\\u043C\\u0432\\u043E\\u043B\\u043E\\u0432',
  ct_errWordTooManyWords: (String word) => '\\u0421\\u043B\\u043E\\u0432\\u043E "${word}" \\u043D\\u0435 \\u0431\\u043E\\u043B\\u0435\\u0435 10 \\u0441\\u043B\\u043E\\u0432',
  ct_errWordDifficulty: (String word) => '\\u0421\\u043B\\u043E\\u0432\\u043E "${word}" \\u0434\\u043E\\u043B\\u0436\\u043D\\u043E \\u0438\\u043C\\u0435\\u0442\\u044C \\u0441\\u043B\\u043E\\u0436\\u043D\\u043E\\u0441\\u0442\\u044C \\u043E\\u0442 1 \\u0434\\u043E 5',
  ct_errFailed: 'Не удалось создать тему',
  et_title: 'Редактировать тему',
  et_edit: 'Редактировать',
  et_save: 'Сохранить',
  et_saving: 'Сохранение...',
  et_nameLabel: 'Название темы',
  et_visibilityLabel: 'Видимость',
  et_addWordsLabel: 'Добавить слова',
  et_addWordsHint: 'Существующие слова нельзя редактировать или удалять',
  et_existingWords: (int count) => '\\u0421\\u0443\\u0449\\u0435\\u0441\\u0442\\u0432\\u0443\\u044E\\u0449\\u0438\\u0435 \\u0441\\u043B\\u043E\\u0432\\u0430 (${count})',
  et_teamsLabel: 'Команды (только просмотр)',
  et_updatingVisibility: 'Обновление...',
  et_errWordDuplicate: (String words) => '\\u0421\\u043B\\u043E\\u0432\\u0430 \\u0443\\u0436\\u0435 \\u0441\\u0443\\u0449\\u0435\\u0441\\u0442\\u0432\\u0443\\u044E\\u0442 \\u0432 \\u0442\\u0435\\u043C\\u0435: ${words}',
  et_errForbidden: 'У вас нет прав для редактирования этой темы',
  et_errFailed: 'Не удалось сохранить изменения',
  et_errVisibility: 'Не удалось обновить видимость',
  rules_title: 'Правила игры Alias',
  rules_basicGameplay: 'Основной геймплей',
  rules_intro: 'Alias — весёлая игра в угадывание слов, в которой команды соревнуются, чтобы угадать как можно больше слов за отведённое время.',
  rules_rule1: 'Игроки делятся на команды',
  rules_rule2: 'По одному игроку от команды играет, пока остальные угадывают',
  rules_rule3: 'Играющий получает слово и должен объяснить его, не называя само слово',
  rules_rule4: 'Товарищи по команде пытаются угадать слово',
  rules_rule5: 'За правильные ответы начисляются очки',
  rules_rule6: 'Раунд заканчивается, когда истекает время или слова закончились',
  rules_scoring: 'Очки',
  rules_score1: 'Правильный ответ: +1 очко',
  rules_score2: 'Штраф за пропуск: -1 очко (если включён)',
  rules_score3: 'Победа: первая команда, набравшая целевое количество очков',
  rules_score4: 'Ничья: если слова закончились — побеждает команда с наибольшим счётом',
  rules_config: 'Настройки игры',
  rules_pointsRequired: 'Очков для победы',
  rules_pointsDesc: 'Целевое количество очков для победы (по умолчанию: 50)',
  rules_roundTimer: 'Таймер раунда',
  rules_roundTimerDesc: 'Лимит времени на раунд (15–300 секунд, по умолчанию: 60)',
  rules_skipPenalty: 'Штраф за пропуск',
  rules_skipPenaltyDesc: 'Включить/отключить вычет очков за пропущенные слова',
  rules_teamsLabel: 'Команды',
  rules_teamsDesc: 'Одновременно могут играть 2–10 команд',
  rules_themeManagement: 'Управление темами',
  rules_feat1: 'Создание тем: создайте собственные темы со своим набором слов',
  rules_feat2: 'Импорт тем: импортируйте темы из внешних источников в формате JSON',
  rules_feat3: 'Фильтрация: по сложности, языку, своим темам, избранным, статусу проверки',
  rules_feat4: 'Поиск: найдите темы по названию или описанию',
  rules_feat5: 'Минимум слов: каждая тема должна содержать не менее 30 слов',
  rules_gameFeatures: 'Возможности игры',
  rules_gameHistory: 'История игр',
  rules_gameHistoryDesc: 'Просматривайте все завершённые игры и отслеживайте статистику',
  rules_gameResumption: 'Продолжение игры',
  rules_gameResumptionDesc: 'Возобновите незавершённые игры с того места, где остановились',
  rules_cheatingDetection: 'Обнаружение читерства',
  rules_cheatingDetectionDesc: 'Отслеживает время начала раундов для предотвращения нечестной игры',
  rules_resultConfirmation: 'Подтверждение результатов',
  rules_resultConfirmationDesc: 'Проверьте и подтвердите результаты раунда перед подсчётом очков',
  rules_howToPlay: 'Как играть',
  rules_step1: 'Выберите тему со словами для угадывания',
  rules_step2: 'Настройте параметры игры (очки, таймер, команды)',
  rules_step3: 'По очереди объясняйте слова своей команде',
  rules_step4: 'Нажмите «Угадано» для правильных ответов, «Пропустить» для сложных слов',
  rules_step5: 'Просмотрите и подтвердите результаты после каждого раунда',
  rules_step6: 'Продолжайте, пока одна из команд не наберёт целевое количество очков',
  rules_difficultyLevels: 'Уровни сложности',
  rules_veryEasy: 'Очень лёгкий',
  rules_easy: 'Лёгкий',
  rules_medium: 'Средний',
  rules_hard: 'Сложный',
  rules_veryHard: 'Очень сложный',
  cs_cheatingTitle: 'Читерство обнаружено',
  cs_cheatingDesc: 'Слишком много слов угадано слишком быстро',
  cs_pausedTitle: 'Раунд на паузе',
  cs_pausedDesc: 'Слово скрыто до возобновления',
);

final Map<String, Translations> locales = {'en': en, 'ru': ru};
